### PR TITLE
docs: Employee Hour Utilisation Report Docs

### PR DESCRIPTION
**Pull request by NagariaHussain**
Docs for https://github.com/frappe/erpnext/pull/25209

report_docs

### CODE REVIEW

**Comment by asbasawaraj** [comment]
@NagariaHussain There are three commits in this PR. Isn't it better to have just one commit. It results is cleaner commit history.

**Review by asbasawaraj — DISMISSED** [review]
Add one commit instead of three as it results in a cleaner commit hostory.

**Comment by NagariaHussain** [comment]
@asbasawaraj Rebased to 1 commit.

**Comment by barredterra** [comment]
@NagariaHussain why change the workflows while adding docs? Was this required for your docs to work?

I suggest to remove the changes to `.github/workflows/nodejs.yml` from this PR and make a separate PR for it.

**Comment by NagariaHussain** [comment]
@barredterra There was an issue at the time I create this PR, but now it is fixed. I will remove that change from this PR. Thanks.

**Review by barredterra — APPROVED** [review]

**Comment by barredterra** [comment]
@NagariaHussain are these docs for a new or existing feature? If new, is the related PR already merged?

**Comment by ruchamahabal** [comment]
@NagariaHussain Can you add docs for **% Utilization (Billed Only)** too?

**Comment by NagariaHussain** [comment]
> @NagariaHussain Can you add docs for **% Utilization (Billed Only)** too?

On it.

**Review by ruchamahabal — APPROVED** [review]

**Pull request merged**
