### PR TITLE
feat: leave Policy Assignment docs refactor

### PR DESCRIPTION
**Pull request by Anurag810**
image

### CODE REVIEW

**Comment by barredterra** [comment]
@Anurag810 docs have been refactored to have a v12 and v13 folder for the respective version of ERPNext. Kindly update your PR to take this new structure into account.

**Review by asbasawaraj — CHANGES_REQUESTED** [review]
Please update PR as per version-specific documentation.

**Comment by Anurag810** [comment]
@asbasawaraj @barredterra Please Review

**Comment by Anurag810** [comment]
@barredterra @asbasawaraj please review this on priority, the feature is already merged.

**Review by pateljannat — APPROVED** [review]

**Pull request merged**
