### PR TITLE
Feat: Taxjar Integration Documentation Added

### PR DESCRIPTION
**Pull request by vishdha**
- [x] Documentation

- [ ] Images

### CODE REVIEW

**Comment by deepeshgarg007** [comment]
@vishdha @Alchez Can you please update the Images and GIF in this so that this can be merged

**Comment by prasadarr** [comment]
@vishdha this PR is missing images, please add them

**Comment by prasadarr** [comment]
@vishdha ??

**Comment by barredterra** [comment]
@prasadarr shall we remove the missing images and merge it as is? Would be a pity to lose this piece of docs.

**Review by asbasawaraj — CHANGES_REQUESTED** [review]
Please update PR as per version-specific documentation.

**Pull request closed without merging**
